repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
# -   repo: https://github.com/econchick/interrogate
#     rev: 2.3.1
#     hooks:
#     -   id: interrogatepre-commit --version