repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [python]
      - id: black
        name: black
        entry: black .
        language: system
        types: [python]
      - id: bandit
        name: bandit
        entry: bandit .
        language: system
        types: [python]
